version: '3.4'

services:
  backend:
    build:
      context: ./
    container_name: vroomv-backend
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3001:3001
    env_file:
      - .env
    links:
      - database
    command: ['npm', 'run', 'dev']
  database:
    image: postgres:latest
    container_name: vroomv-database
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vroomv
    volumes:
      - ./pgData:/var/lib/postgresql/data/pgdata
